[package]
name = "p8020a"
version = "0.1.0"
edition = "2021"
authors = ["Andrzej Hunt"]

[lib]
name = "p8020a"
crate-type = ["staticlib"]

[dependencies]
clap = {version = "4.5.13", features = ["derive"] }
serialport = "4.4.0"
time = {version = "0.3.36", features = ["formatting", "macros"] }
